### ISSUE TITLE
Comment here to be added as a collaborator

### ISSUE THREAD

**Issue by brianamarie** [githubschool/13-dec#1]
We will use a script to add everyone as collaborators, but first, you'll need to comment here. 

What would you like to learn about GitHub?

**Comment by githubteacher** [comment]
https://githubtraining.github.io/training-manual-gh4m/#/

**Comment by LcMy** [comment]
document management

**Comment by fagen84** [comment]
second

**Comment by qb444** [comment]
My comment

**Comment by richsil** [comment]
Hello from Data Services

**Comment by bobbelsche** [comment]
Leaved the comment

**Comment by eq203** [comment]
Hi Briana, 
I am looking foward to get to know GitHub.
Cheers,
Arne

**Comment by hubertkret** [comment]
I would like to learn the features of github which are useful for document management and team communication

**Comment by fagen84** [comment]
streber

**Comment by UweSchweickert** [comment]
silence is golden

**Comment by aorlov5** [comment]
last one from Energy IT

**Comment by kipkaeske** [comment]
why can I not use the account I already have?

**Comment by xx250** [comment]
Just got it :-)

**Comment by UweSchweickert** [comment]
🌞

**Comment by le649** [comment]
first contact established

**Comment by UweSchweickert** [comment]
🐢 ...

**Comment by gloriapfaue** [comment]
done

**Comment by UweSchweickert** [comment]
>           on
