### ISSUE TITLE
Helpful Links

### ISSUE THREAD

**Issue by brianamarie** [githubschool/13-dec#37]
## Helpful Links 

Here are a few helpful links throughout class: 

### Training Manual 
- [Training Manual](https://githubtraining.github.io/training-manual-gh4m/#)

### In-Class Links 
- [CircleCI](https://www.circleci.com/)
- [Heroku](https://www.heroku.com/)
- [Docsify](https://docsify.js.org/)

### General Resources 
- [Learning Lab](https://lab.github.com/)
- [Markdown cheatsheet](https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf)
- [GitHub Flow](https://guides.github.com/introduction/flow/)

**Comment by kipkaeske** [comment]
[Mastering Markdown](https://guides.github.com/features/mastering-markdown/)
